language: generic
dist: xenial

matrix:
  include:
    - os: linux
      arch: amd64
      compiler: g++
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - CXX=g++-9 BUILD=Release
before_install:  
  - CXX=g++-10 BUILD=Release
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/g++-9 /usr/bin/g++
  - g++ --version
  - >
    if [ ! -f boost_1_72_0 ]; then
        wget https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz;
        tar -xf boost_1_72_0.tar.gz
        cd boost_1_72_0;
        sudo ./bootstrap.sh --prefix=/usr/local --with-libraries=all;
        cd ..;
    fi
    cd boost_1_72_0;
    sudo ./b2 -j16 install;
    sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/boost.conf';
    sudo ldconfig;
    cd ..
  - >
    if [ ! -f cmake-3.20.0-rc3 ]; then
        wget https://github.com/Kitware/CMake/releases/download/v3.20.0-rc3/cmake-3.20.0-rc3.tar.gz
        tar -xf cmake-3.20.0-rc3.tar.gz
        cd cmake-3.20.0-rc3
        ./configure
        make -j16
        cd ..
    fi
    cd cmake-3.20.0-rc3
    make install
    cd ..
  - >
cache:
  directories:
    - boost_1_72_0
    - cmake-3.20.0-rc3
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake .. 
     - make
     - make RunTests
     
